version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend/GymNotes
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend/GymNotes:/app
      - /root/.m2
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: gymnotes-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
